### ISSUE TITLE
Tool bar hides the top of long blocks.

### ISSUE THREAD

**Issue by nathgilson** [unlayer/react-email-editor#179]
<img width="672" alt="Screenshot 2021-03-16 at 16 36 01" src="https://user-images.githubusercontent.com/28766479/111345988-b3287200-8675-11eb-919c-5c72523def19.png">

There is no way to edit the hidden part of the block. How can I fix it?

**Comment by adeelraza** [comment]
@nathgilson It should readjust itself when you scroll down?

**Comment by nathgilson** [comment]
Hello Adeel,

If I scroll down I can't edit the top of the block neither:

[image: Screenshot 2021-03-18 at 12.56.32.png]

I've tried many different things but there is truly no way to edit the top
of a long text block.
The solution would be to keep the toolbar at the bottom of the block like
this (remove the function that changes the css value of "top"):

[image: Screenshot 2021-03-18 at 13.01.05.png]

Nathan

**Comment by murraygray** [comment]
how has this bug been open since 2021?????? 

it's affecting our users on a daily basis.

wow - I'm starting to really regret choosing this plugin.

**Comment by adeelraza** [comment]
@murraygray this was fixed but has re-appeared in a different variation. We are currently actively working to resolve it.

**Comment by murraygray** [comment]
great to hear.  any chance there can be more descriptive statuses on these issues?  

"Open" really tells us nothing and does you guys no favors.

**Comment by murraygray** [comment]
How is this still an active issue guys???????!!!!!

**Comment by khashaba** [comment]
Hi @murraygray 

Thank you for following up, and we truly appreciate your patience on this. Apologies for the delay in resolving this—it’s been a bit of a journey, as we wanted to ensure the fix was thoroughly tested and wouldn’t introduce any new issues.

The good news is that it’s now been addressed in the latest version. We truly appreciate your understanding and your engagement—it helps us improve! 

Please give it a try and let us know if there’s anything else we can assist with.

**Comment by murraygray** [comment]
@khashaba we've installed the latest version on our staging server and it's STILL not working: https://share.zight.com/6quADQp1

**Comment by brunolemos** [comment]
@murraygray you need to pass `version: "latest"` to your `init` config to use the `latest` version, otherwise it will use the `stable` channel by default.

If you already did that, please type `unlayer.versions` in the browser console and let us know which version it's currently using. It should be `1.188.0` or newer.
